version: '3.8'

services:
  # Backend Spring Boot application
  backend:
    build: ./be
    container_name: hi-tech-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webhitech?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - web-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hi-tech-mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=webhitech
    networks:
      - web-network
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  frontend:
    build: ./fe
    container_name: hi-tech-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://${IP}:8080/web
    depends_on:
      - backend
    networks:
      - web-network
    restart: unless-stopped

networks:
  web-network:
    driver: bridge
