version: '3.8'

services:
  # Backend Spring Boot application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-soict-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webhitech?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - web-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: web-soict-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=webhitech
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - web-network
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  # Optional phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-soict-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - web-network
    restart: unless-stopped

networks:
  web-network:
    driver: bridge

volumes:
  mysql-data: