export const PERMISSIONS = {
    // Product Permissions
    GET_ALL_GOODS: "GET_ALL_GOODS",
    CREATE_GOODS: "CREATE_GOODS",
    UPDATE_GOODS: "UPDATE_GOODS",
    DELETE_GOODS: "DELETE_GOODS",
    GET_GOODS: "GET_GOODS",

    // User Permissions
    GET_ALL_USERS: "GET_ALL_USERS",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    GET_USER: "GET_USER",

    // Role Permissions
    GET_ALL_ROLES: "GET_ALL_ROLES",
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",

    // Permission Management
    CREATE_PERMISSION: "CREATE_PERMISSION",
    DELETE_PERMISSION: "DELETE_PERMISSION",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    GET_ALL_PERMISSIONS: "GET_ALL_PERMISSIONS",
    ASSIGN_PERMISSION_TO_ROLE: "ASSIGN_PERMISSION_TO_ROLE",

    // Voucher Permissions
    CREATE_VOUCHER: "CREATE_VOUCHER",
    DELETE_VOUCHER: "DELETE_VOUCHER",
    GET_VOUCHER: "GET_VOUCHER",
};
