name: learn-github-actions 
# name có thể đặt tùy ý, nhưng nên có ý nghĩa với nội dung của file
# run-name: ${{github.actor}} is learning Github actions
run-name: ${{github.actor}} is learning Github actions
on: [push]
# on: [push, pull_request] nghĩa là khi có push hoặc pull request thì sẽ chạy workflow này
jobs:
  check-bats-version:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g bats
      - run: bats -v