name: Deploy to VPS

on:
  push:
    branches:
      - be
      - fe

jobs:
  deploy-backend:
    if: github.ref == 'refs/heads/Harkins'
    runs-on: ubuntu-latest
    steps:
      - name: Check out backend code
        uses: actions/checkout@v3

      - name: Copy backend source to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          # Copy everything in the repo (backend)
          source: "."
          target: /home/${{ secrets.VPS_USER }}/backend

      - name: Deploy backend via Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/backend
            docker compose up --build

  deploy-frontend:
    if: github.ref == 'refs/heads/fe'
    runs-on: ubuntu-latest
    steps:
      - name: Check out frontend code
        uses: actions/checkout@v3

      - name: Copy frontend code to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "."
          target: /home/${{ secrets.VPS_USER }}/frontend

      - name: Build & run frontend Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/frontend
            docker build -t fe:latest .
            docker stop fe || true
            docker rm fe  || true
            docker run -d --restart always -p 80:80 --name fe fe:latest
