name: 🛫 Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action (for metadata)
        uses: actions/checkout@v4

      - name: Pull/clone & deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          password: ${{ vars.VPS_PASSWORD }}
          port: 22
          script: |
            # where you want your app on the VPS
            APP_DIR=/app

            # if it's not there yet, clone; otherwise pull
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/${{ github.repository }}.git "$APP_DIR"
            else
              cd "$APP_DIR"
              git pull origin main
            fi

            # finally, rebuild & restart
            cd "$APP_DIR"
            export IP=${{ vars.VPS_HOST }}
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker compose up --build -d
