name: Copy code to folder be and fe

permissions:
  contents: write

on:
  push:
    branches:
      - Harkins
      - fe

jobs:
  update-subtree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update subtree
        run: |
          BRANCH=${{ github.ref_name }}
          case "$BRANCH" in
            Harkins) git subtree pull --prefix=be  origin Harkins ;;
            fe)      git subtree pull --prefix=fe  origin fe      ;;
            *)       echo "No matching subtree for $BRANCH"; exit 0 ;;
          esac

      - name: Push changes
        run: git push origin main
